//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TOS.ITosService")]
    public interface ITosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YapKurumTopluOdeme", ReplyAction="http://tempuri.org/YapKurumTopluOdeme")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeOutput VitTosIslem(TOS.TopluOdemeInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YapKurumTopluOdeme", ReplyAction="http://tempuri.org/YapKurumTopluOdeme")]
        System.Threading.Tasks.Task<TOS.TopluOdemeOutput> VitTosIslemAsync(TOS.TopluOdemeInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YapKurumTopluOdemeSwift", ReplyAction="http://tempuri.org/YapKurumTopluOdemeSwift")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeSwiftOutput VitTosSwiftIslem(TOS.TopluOdemeSwiftInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YapKurumTopluOdemeSwift", ReplyAction="http://tempuri.org/YapKurumTopluOdemeSwift")]
        System.Threading.Tasks.Task<TOS.TopluOdemeSwiftOutput> VitTosSwiftIslemAsync(TOS.TopluOdemeSwiftInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VitTosIptal", ReplyAction="http://tempuri.org/VitTosIptal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeIptalOutput VitTosIptal(TOS.VitTosIptalIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VitTosIptal", ReplyAction="http://tempuri.org/VitTosIptal")]
        System.Threading.Tasks.Task<TOS.TopluOdemeIptalOutput> VitTosIptalAsync(TOS.VitTosIptalIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsSifreGonder", ReplyAction="http://tempuri.org/SmsSifreGonder")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeSmsSifreGonderOutput SmsSifreGonder(TOS.SmsSifreGonderIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsSifreGonder", ReplyAction="http://tempuri.org/SmsSifreGonder")]
        System.Threading.Tasks.Task<TOS.TopluOdemeSmsSifreGonderOutput> SmsSifreGonderAsync(TOS.SmsSifreGonderIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsSifreOnay", ReplyAction="http://tempuri.org/SmsSifreOnay")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeSmsSifreOnayOutput SmsSifreOnay(TOS.SmsSifreOnayIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmsSifreOnay", ReplyAction="http://tempuri.org/SmsSifreOnay")]
        System.Threading.Tasks.Task<TOS.TopluOdemeSmsSifreOnayOutput> SmsSifreOnayAsync(TOS.SmsSifreOnayIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnayTamam", ReplyAction="http://tempuri.org/OnayTamam")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeOnayTamamOutput OnayTamam(TOS.OnayTamamIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnayTamam", ReplyAction="http://tempuri.org/OnayTamam")]
        System.Threading.Tasks.Task<TOS.TopluOdemeOnayTamamOutput> OnayTamamAsync(TOS.OnayTamamIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VitTosSorgulaIslem", ReplyAction="http://tempuri.org/VitTosSorgulaIslem")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeSorgulaIslemOutput VitTosSorgulaIslem(TOS.TopluOdemeSorgulaIslemInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VitTosSorgulaIslem", ReplyAction="http://tempuri.org/VitTosSorgulaIslem")]
        System.Threading.Tasks.Task<TOS.TopluOdemeSorgulaIslemOutput> VitTosSorgulaIslemAsync(TOS.TopluOdemeSorgulaIslemInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KontrolEtAdSoyadHesapBilgisi", ReplyAction="http://tempuri.org/KontrolEtAdSoyadHesapBilgisi")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TOS.TopluOdemeAdSoyadKontrolOutput KontrolEtAdSoyadHesapBilgisi(TOS.TopluOdemeAdSoyadKontrolInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KontrolEtAdSoyadHesapBilgisi", ReplyAction="http://tempuri.org/KontrolEtAdSoyadHesapBilgisi")]
        System.Threading.Tasks.Task<TOS.TopluOdemeAdSoyadKontrolOutput> KontrolEtAdSoyadHesapBilgisiAsync(TOS.TopluOdemeAdSoyadKontrolInput request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecuredWebServiceHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AdSoyadKontrolSonuc
    {
        
        private string aliciHesapIbanNoField;
        
        private string kurumKoduField;
        
        private string aliciAdSoyadField;
        
        private string aliciBankaKoduField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AliciHesapIbanNo
        {
            get
            {
                return this.aliciHesapIbanNoField;
            }
            set
            {
                this.aliciHesapIbanNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AliciAdSoyad
        {
            get
            {
                return this.aliciAdSoyadField;
            }
            set
            {
                this.aliciAdSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AliciBankaKodu
        {
            get
            {
                return this.aliciBankaKoduField;
            }
            set
            {
                this.aliciBankaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosSorgulaIslemSonuc
    {
        
        private string kurumKoduField;
        
        private KayitTipleri kayitTipiField;
        
        private bool vergiTcKontrolEdilsinField;
        
        private bool krediKullanilsinField;
        
        private decimal islemTutariField;
        
        private DovizCinsleri dovizCinsiField;
        
        private string kaynakSubeKoduField;
        
        private string kaynakHesapNoField;
        
        private string aliciHesapNoField;
        
        private string aliciSubeKoduField;
        
        private string aliciBankaKoduField;
        
        private string aliciAdiField;
        
        private string aciklamaField;
        
        private string aliciAdresField;
        
        private string aliciTelField;
        
        private string aliciTcVergiNoField;
        
        private string aliciVergiDairesiField;
        
        private string aliciBabaAdiField;
        
        private string aliciEmailField;
        
        private string odemeTarihiField;
        
        private string paketNoField;
        
        private string kurumIslemIdField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        private string sorguNoField;
        
        private string islemNoField;
        
        private string ekstreAciklamasiField;
        
        private string iadeTarihiField;
        
        private string transferTarihiField;
        
        private string iadeIslemSorguNumarasiField;
        
        private string iadeIslemNoField;
        
        private SonucDurumKodlari islemDurumuField;
        
        private string aliciBankaAdiField;
        
        private SwiftIslemDetaylari swiftIslemDetayiField;
        
        private string swiftMasrafTipiField;
        
        private string swiftMasrafHesapNoField;
        
        private int swiftIslemMahiyetiKoduField;
        
        private string swiftIslemMahiyetiAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KayitTipleri KayitTipi
        {
            get
            {
                return this.kayitTipiField;
            }
            set
            {
                this.kayitTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool VergiTcKontrolEdilsin
        {
            get
            {
                return this.vergiTcKontrolEdilsinField;
            }
            set
            {
                this.vergiTcKontrolEdilsinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool KrediKullanilsin
        {
            get
            {
                return this.krediKullanilsinField;
            }
            set
            {
                this.krediKullanilsinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal IslemTutari
        {
            get
            {
                return this.islemTutariField;
            }
            set
            {
                this.islemTutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DovizCinsleri DovizCinsi
        {
            get
            {
                return this.dovizCinsiField;
            }
            set
            {
                this.dovizCinsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string KaynakSubeKodu
        {
            get
            {
                return this.kaynakSubeKoduField;
            }
            set
            {
                this.kaynakSubeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string KaynakHesapNo
        {
            get
            {
                return this.kaynakHesapNoField;
            }
            set
            {
                this.kaynakHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AliciHesapNo
        {
            get
            {
                return this.aliciHesapNoField;
            }
            set
            {
                this.aliciHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AliciSubeKodu
        {
            get
            {
                return this.aliciSubeKoduField;
            }
            set
            {
                this.aliciSubeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AliciBankaKodu
        {
            get
            {
                return this.aliciBankaKoduField;
            }
            set
            {
                this.aliciBankaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AliciAdi
        {
            get
            {
                return this.aliciAdiField;
            }
            set
            {
                this.aliciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AliciAdres
        {
            get
            {
                return this.aliciAdresField;
            }
            set
            {
                this.aliciAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AliciTel
        {
            get
            {
                return this.aliciTelField;
            }
            set
            {
                this.aliciTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AliciTcVergiNo
        {
            get
            {
                return this.aliciTcVergiNoField;
            }
            set
            {
                this.aliciTcVergiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AliciVergiDairesi
        {
            get
            {
                return this.aliciVergiDairesiField;
            }
            set
            {
                this.aliciVergiDairesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AliciBabaAdi
        {
            get
            {
                return this.aliciBabaAdiField;
            }
            set
            {
                this.aliciBabaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AliciEmail
        {
            get
            {
                return this.aliciEmailField;
            }
            set
            {
                this.aliciEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string OdemeTarihi
        {
            get
            {
                return this.odemeTarihiField;
            }
            set
            {
                this.odemeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string KurumIslemId
        {
            get
            {
                return this.kurumIslemIdField;
            }
            set
            {
                this.kurumIslemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string SorguNo
        {
            get
            {
                return this.sorguNoField;
            }
            set
            {
                this.sorguNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string IslemNo
        {
            get
            {
                return this.islemNoField;
            }
            set
            {
                this.islemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string EkstreAciklamasi
        {
            get
            {
                return this.ekstreAciklamasiField;
            }
            set
            {
                this.ekstreAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string IadeTarihi
        {
            get
            {
                return this.iadeTarihiField;
            }
            set
            {
                this.iadeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string TransferTarihi
        {
            get
            {
                return this.transferTarihiField;
            }
            set
            {
                this.transferTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string IadeIslemSorguNumarasi
        {
            get
            {
                return this.iadeIslemSorguNumarasiField;
            }
            set
            {
                this.iadeIslemSorguNumarasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string IadeIslemNo
        {
            get
            {
                return this.iadeIslemNoField;
            }
            set
            {
                this.iadeIslemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public SonucDurumKodlari IslemDurumu
        {
            get
            {
                return this.islemDurumuField;
            }
            set
            {
                this.islemDurumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string AliciBankaAdi
        {
            get
            {
                return this.aliciBankaAdiField;
            }
            set
            {
                this.aliciBankaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public SwiftIslemDetaylari SwiftIslemDetayi
        {
            get
            {
                return this.swiftIslemDetayiField;
            }
            set
            {
                this.swiftIslemDetayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string SwiftMasrafTipi
        {
            get
            {
                return this.swiftMasrafTipiField;
            }
            set
            {
                this.swiftMasrafTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string SwiftMasrafHesapNo
        {
            get
            {
                return this.swiftMasrafHesapNoField;
            }
            set
            {
                this.swiftMasrafHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int SwiftIslemMahiyetiKodu
        {
            get
            {
                return this.swiftIslemMahiyetiKoduField;
            }
            set
            {
                this.swiftIslemMahiyetiKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string SwiftIslemMahiyetiAciklama
        {
            get
            {
                return this.swiftIslemMahiyetiAciklamaField;
            }
            set
            {
                this.swiftIslemMahiyetiAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum KayitTipleri
    {
        
        /// <remarks/>
        Hesap,
        
        /// <remarks/>
        Isim,
        
        /// <remarks/>
        IcraE,
        
        /// <remarks/>
        IcraS,
        
        /// <remarks/>
        IcraB,
        
        /// <remarks/>
        KrediKarti,
        
        /// <remarks/>
        Iade,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DovizCinsleri
    {
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        GBP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SonucDurumKodlari
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Islemde,
        
        /// <remarks/>
        Basarili,
        
        /// <remarks/>
        Hatali,
        
        /// <remarks/>
        TekrarDenenebilir,
        
        /// <remarks/>
        MukerrerIstek,
        
        /// <remarks/>
        HesabaGeciyor,
        
        /// <remarks/>
        IleriTarihliOdenecek,
        
        /// <remarks/>
        IptalEdildi,
        
        /// <remarks/>
        IadeEdildi,
        
        /// <remarks/>
        Yuklendi,
        
        /// <remarks/>
        TeyitBekleniyor,
        
        /// <remarks/>
        SwiftSonucuBekleniyor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SwiftIslemDetaylari
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        MalMukabili,
        
        /// <remarks/>
        PesinIthalat,
        
        /// <remarks/>
        GorunmeyenKalem,
        
        /// <remarks/>
        GidenHavale,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosSorgulaIslemIstek
    {
        
        private string kurumKoduField;
        
        private KayitTipleri kayitTipiField;
        
        private SonucDurumKodlari islemDurumuField;
        
        private string kaynakHesapNoField;
        
        private string aliciHesapNoField;
        
        private string kurumIslemIdField;
        
        private string odemeTarihiField;
        
        private string islemNumarasiField;
        
        private string paketNoField;
        
        private string sorguNoField;
        
        private string iadeTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KayitTipleri KayitTipi
        {
            get
            {
                return this.kayitTipiField;
            }
            set
            {
                this.kayitTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SonucDurumKodlari IslemDurumu
        {
            get
            {
                return this.islemDurumuField;
            }
            set
            {
                this.islemDurumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KaynakHesapNo
        {
            get
            {
                return this.kaynakHesapNoField;
            }
            set
            {
                this.kaynakHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AliciHesapNo
        {
            get
            {
                return this.aliciHesapNoField;
            }
            set
            {
                this.aliciHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string KurumIslemId
        {
            get
            {
                return this.kurumIslemIdField;
            }
            set
            {
                this.kurumIslemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OdemeTarihi
        {
            get
            {
                return this.odemeTarihiField;
            }
            set
            {
                this.odemeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IslemNumarasi
        {
            get
            {
                return this.islemNumarasiField;
            }
            set
            {
                this.islemNumarasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SorguNo
        {
            get
            {
                return this.sorguNoField;
            }
            set
            {
                this.sorguNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IadeTarihi
        {
            get
            {
                return this.iadeTarihiField;
            }
            set
            {
                this.iadeTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OnayTamamSonuc
    {
        
        private string[] paketNoField;
        
        private string kurumKoduField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsSifreOnaySonuc
    {
        
        private string smsSifreField;
        
        private string kurumKoduField;
        
        private string telefonNoField;
        
        private string islemRefNoField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SmsSifre
        {
            get
            {
                return this.smsSifreField;
            }
            set
            {
                this.smsSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TelefonNo
        {
            get
            {
                return this.telefonNoField;
            }
            set
            {
                this.telefonNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IslemRefNo
        {
            get
            {
                return this.islemRefNoField;
            }
            set
            {
                this.islemRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsSifreGonderSonuc
    {
        
        private string[] paketNoField;
        
        private string telefonNoField;
        
        private string islemRefNoField;
        
        private string kurumKoduField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TelefonNo
        {
            get
            {
                return this.telefonNoField;
            }
            set
            {
                this.telefonNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IslemRefNo
        {
            get
            {
                return this.islemRefNoField;
            }
            set
            {
                this.islemRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosIptalSonuc
    {
        
        private string kurumIslemIdField;
        
        private string kurumKoduField;
        
        private string paketNoField;
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KurumIslemId
        {
            get
            {
                return this.kurumIslemIdField;
            }
            set
            {
                this.kurumIslemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VitTosSwiftIslemSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosSwiftIslemIstek
    {
        
        private string kurumKoduField;
        
        private SwiftIslemDetaylari swiftIslemDetayiField;
        
        private string masrafField;
        
        private decimal islemTutariField;
        
        private string odemeTarihiField;
        
        private string dovizCinsiField;
        
        private string kaynakHesapNoField;
        
        private string aliciHesapIbanNoField;
        
        private SwiftHesapIbanDurumlari aliciHesapIbanDurumuField;
        
        private string aliciBankaBicField;
        
        private string aliciSubeKoduField;
        
        private string aliciBankaAdiField;
        
        private string aliciAdiField;
        
        private string swiftAciklamaField;
        
        private string kurumIslemIdField;
        
        private string aliciAdresField;
        
        private string paketNoField;
        
        private string gumrukBelgeNoField;
        
        private string gumrukBelgeTarihiField;
        
        private string faturaNoField;
        
        private string faturaTarihiField;
        
        private string swiftMasrafHesapNoField;
        
        private int swiftIslemMahiyetiKoduField;
        
        private string swiftIslemMahiyetiAciklamaField;
        
        private string lehdarYerelBankaKoduField;
        
        private string araciBankaBicKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SwiftIslemDetaylari SwiftIslemDetayi
        {
            get
            {
                return this.swiftIslemDetayiField;
            }
            set
            {
                this.swiftIslemDetayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Masraf
        {
            get
            {
                return this.masrafField;
            }
            set
            {
                this.masrafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal IslemTutari
        {
            get
            {
                return this.islemTutariField;
            }
            set
            {
                this.islemTutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OdemeTarihi
        {
            get
            {
                return this.odemeTarihiField;
            }
            set
            {
                this.odemeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DovizCinsi
        {
            get
            {
                return this.dovizCinsiField;
            }
            set
            {
                this.dovizCinsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string KaynakHesapNo
        {
            get
            {
                return this.kaynakHesapNoField;
            }
            set
            {
                this.kaynakHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AliciHesapIbanNo
        {
            get
            {
                return this.aliciHesapIbanNoField;
            }
            set
            {
                this.aliciHesapIbanNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public SwiftHesapIbanDurumlari AliciHesapIbanDurumu
        {
            get
            {
                return this.aliciHesapIbanDurumuField;
            }
            set
            {
                this.aliciHesapIbanDurumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AliciBankaBic
        {
            get
            {
                return this.aliciBankaBicField;
            }
            set
            {
                this.aliciBankaBicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AliciSubeKodu
        {
            get
            {
                return this.aliciSubeKoduField;
            }
            set
            {
                this.aliciSubeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AliciBankaAdi
        {
            get
            {
                return this.aliciBankaAdiField;
            }
            set
            {
                this.aliciBankaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AliciAdi
        {
            get
            {
                return this.aliciAdiField;
            }
            set
            {
                this.aliciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SwiftAciklama
        {
            get
            {
                return this.swiftAciklamaField;
            }
            set
            {
                this.swiftAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string KurumIslemId
        {
            get
            {
                return this.kurumIslemIdField;
            }
            set
            {
                this.kurumIslemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AliciAdres
        {
            get
            {
                return this.aliciAdresField;
            }
            set
            {
                this.aliciAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string GumrukBelgeNo
        {
            get
            {
                return this.gumrukBelgeNoField;
            }
            set
            {
                this.gumrukBelgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string GumrukBelgeTarihi
        {
            get
            {
                return this.gumrukBelgeTarihiField;
            }
            set
            {
                this.gumrukBelgeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string FaturaNo
        {
            get
            {
                return this.faturaNoField;
            }
            set
            {
                this.faturaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string FaturaTarihi
        {
            get
            {
                return this.faturaTarihiField;
            }
            set
            {
                this.faturaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string SwiftMasrafHesapNo
        {
            get
            {
                return this.swiftMasrafHesapNoField;
            }
            set
            {
                this.swiftMasrafHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int SwiftIslemMahiyetiKodu
        {
            get
            {
                return this.swiftIslemMahiyetiKoduField;
            }
            set
            {
                this.swiftIslemMahiyetiKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string SwiftIslemMahiyetiAciklama
        {
            get
            {
                return this.swiftIslemMahiyetiAciklamaField;
            }
            set
            {
                this.swiftIslemMahiyetiAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string LehdarYerelBankaKodu
        {
            get
            {
                return this.lehdarYerelBankaKoduField;
            }
            set
            {
                this.lehdarYerelBankaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string AraciBankaBicKodu
        {
            get
            {
                return this.araciBankaBicKoduField;
            }
            set
            {
                this.araciBankaBicKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SwiftHesapIbanDurumlari
    {
        
        /// <remarks/>
        Hesap,
        
        /// <remarks/>
        Iban,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosSwiftIslemSonuc : VitTosSwiftIslemIstek
    {
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        private string sorguNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SorguNo
        {
            get
            {
                return this.sorguNoField;
            }
            set
            {
                this.sorguNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VitTosIslemSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosIslemIstek
    {
        
        private string kurumKoduField;
        
        private KayitTipleri kayitTipiField;
        
        private bool vergiTcKontrolEdilsinField;
        
        private bool krediKullanilsinField;
        
        private decimal islemTutariField;
        
        private string dovizCinsiField;
        
        private string kaynakHesapNoField;
        
        private string aliciHesapNoField;
        
        private string aliciBankaKoduField;
        
        private string aliciSubeKoduField;
        
        private string aliciAdiField;
        
        private string aciklamaField;
        
        private string kurumIslemIdField;
        
        private string aliciAdresField;
        
        private string aliciTelField;
        
        private string aliciTcVergiNoField;
        
        private string aliciVergiDairesiField;
        
        private string aliciBabaAdiField;
        
        private string aliciEmailField;
        
        private string odemeTarihiField;
        
        private string paketNoField;
        
        private string gelenIadeOdemeTarihiField;
        
        private string gelenIadeIslemSorguNumarasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KayitTipleri KayitTipi
        {
            get
            {
                return this.kayitTipiField;
            }
            set
            {
                this.kayitTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool VergiTcKontrolEdilsin
        {
            get
            {
                return this.vergiTcKontrolEdilsinField;
            }
            set
            {
                this.vergiTcKontrolEdilsinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool KrediKullanilsin
        {
            get
            {
                return this.krediKullanilsinField;
            }
            set
            {
                this.krediKullanilsinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal IslemTutari
        {
            get
            {
                return this.islemTutariField;
            }
            set
            {
                this.islemTutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DovizCinsi
        {
            get
            {
                return this.dovizCinsiField;
            }
            set
            {
                this.dovizCinsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string KaynakHesapNo
        {
            get
            {
                return this.kaynakHesapNoField;
            }
            set
            {
                this.kaynakHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AliciHesapNo
        {
            get
            {
                return this.aliciHesapNoField;
            }
            set
            {
                this.aliciHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AliciBankaKodu
        {
            get
            {
                return this.aliciBankaKoduField;
            }
            set
            {
                this.aliciBankaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AliciSubeKodu
        {
            get
            {
                return this.aliciSubeKoduField;
            }
            set
            {
                this.aliciSubeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AliciAdi
        {
            get
            {
                return this.aliciAdiField;
            }
            set
            {
                this.aliciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string KurumIslemId
        {
            get
            {
                return this.kurumIslemIdField;
            }
            set
            {
                this.kurumIslemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AliciAdres
        {
            get
            {
                return this.aliciAdresField;
            }
            set
            {
                this.aliciAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AliciTel
        {
            get
            {
                return this.aliciTelField;
            }
            set
            {
                this.aliciTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AliciTcVergiNo
        {
            get
            {
                return this.aliciTcVergiNoField;
            }
            set
            {
                this.aliciTcVergiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AliciVergiDairesi
        {
            get
            {
                return this.aliciVergiDairesiField;
            }
            set
            {
                this.aliciVergiDairesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AliciBabaAdi
        {
            get
            {
                return this.aliciBabaAdiField;
            }
            set
            {
                this.aliciBabaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AliciEmail
        {
            get
            {
                return this.aliciEmailField;
            }
            set
            {
                this.aliciEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string OdemeTarihi
        {
            get
            {
                return this.odemeTarihiField;
            }
            set
            {
                this.odemeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PaketNo
        {
            get
            {
                return this.paketNoField;
            }
            set
            {
                this.paketNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string GelenIadeOdemeTarihi
        {
            get
            {
                return this.gelenIadeOdemeTarihiField;
            }
            set
            {
                this.gelenIadeOdemeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string GelenIadeIslemSorguNumarasi
        {
            get
            {
                return this.gelenIadeIslemSorguNumarasiField;
            }
            set
            {
                this.gelenIadeIslemSorguNumarasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VitTosIslemSonuc : VitTosIslemIstek
    {
        
        private string durumKoduField;
        
        private string durumKoduAciklamaField;
        
        private string sorguNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DurumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DurumKoduAciklama
        {
            get
            {
                return this.durumKoduAciklamaField;
            }
            set
            {
                this.durumKoduAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SorguNo
        {
            get
            {
                return this.sorguNoField;
            }
            set
            {
                this.sorguNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeInput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeInput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosIslemIstek[] TopluIslemListesi;
        
        public TopluOdemeInput()
        {
        }
        
        public TopluOdemeInput(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, TOS.VitTosIslemIstek[] TopluIslemListesi)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.TopluIslemListesi = TopluIslemListesi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosIslemSonuc[] OdemeSonucListesi;
        
        public TopluOdemeOutput()
        {
        }
        
        public TopluOdemeOutput(TOS.VitTosIslemSonuc[] OdemeSonucListesi)
        {
            this.OdemeSonucListesi = OdemeSonucListesi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSwiftInput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSwiftInput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosSwiftIslemIstek[] TopluIslemListesi;
        
        public TopluOdemeSwiftInput()
        {
        }
        
        public TopluOdemeSwiftInput(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, TOS.VitTosSwiftIslemIstek[] TopluIslemListesi)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.TopluIslemListesi = TopluIslemListesi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSwiftOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSwiftOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosSwiftIslemSonuc[] OdemeSonucListesi;
        
        public TopluOdemeSwiftOutput()
        {
        }
        
        public TopluOdemeSwiftOutput(TOS.VitTosSwiftIslemSonuc[] OdemeSonucListesi)
        {
            this.OdemeSonucListesi = OdemeSonucListesi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VitTosIptalIstek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VitTosIptalIstek
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string KurumIslemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string KurumKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string PaketNo;
        
        public VitTosIptalIstek()
        {
        }
        
        public VitTosIptalIstek(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, string KurumIslemId, string KurumKodu, string PaketNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.KurumIslemId = KurumIslemId;
            this.KurumKodu = KurumKodu;
            this.PaketNo = PaketNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeIptalOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeIptalOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosIptalSonuc VitTosIptalSonuc;
        
        public TopluOdemeIptalOutput()
        {
        }
        
        public TopluOdemeIptalOutput(TOS.VitTosIptalSonuc VitTosIptalSonuc)
        {
            this.VitTosIptalSonuc = VitTosIptalSonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSifreGonderIstek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmsSifreGonderIstek
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IslemRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string KurumKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] PaketNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string TelefonNo;
        
        public SmsSifreGonderIstek()
        {
        }
        
        public SmsSifreGonderIstek(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, string IslemRefNo, string KurumKodu, string[] PaketNo, string TelefonNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.IslemRefNo = IslemRefNo;
            this.KurumKodu = KurumKodu;
            this.PaketNo = PaketNo;
            this.TelefonNo = TelefonNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSmsSifreGonderOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSmsSifreGonderOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.SmsSifreGonderSonuc SmsSifreGonderSonuc;
        
        public TopluOdemeSmsSifreGonderOutput()
        {
        }
        
        public TopluOdemeSmsSifreGonderOutput(TOS.SmsSifreGonderSonuc SmsSifreGonderSonuc)
        {
            this.SmsSifreGonderSonuc = SmsSifreGonderSonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSifreOnayIstek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmsSifreOnayIstek
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IslemRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string KurumKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SmsSifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string TelefonNo;
        
        public SmsSifreOnayIstek()
        {
        }
        
        public SmsSifreOnayIstek(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, string IslemRefNo, string KurumKodu, string SmsSifre, string TelefonNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.IslemRefNo = IslemRefNo;
            this.KurumKodu = KurumKodu;
            this.SmsSifre = SmsSifre;
            this.TelefonNo = TelefonNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSmsSifreOnayOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSmsSifreOnayOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.SmsSifreOnaySonuc SifreOnaySonuc;
        
        public TopluOdemeSmsSifreOnayOutput()
        {
        }
        
        public TopluOdemeSmsSifreOnayOutput(TOS.SmsSifreOnaySonuc SifreOnaySonuc)
        {
            this.SifreOnaySonuc = SifreOnaySonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnayTamamIstek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OnayTamamIstek
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string KurumKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] PaketNo;
        
        public OnayTamamIstek()
        {
        }
        
        public OnayTamamIstek(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, string KurumKodu, string[] PaketNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.KurumKodu = KurumKodu;
            this.PaketNo = PaketNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeOnayTamamOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeOnayTamamOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.OnayTamamSonuc OnayTamamSonuc;
        
        public TopluOdemeOnayTamamOutput()
        {
        }
        
        public TopluOdemeOnayTamamOutput(TOS.OnayTamamSonuc OnayTamamSonuc)
        {
            this.OnayTamamSonuc = OnayTamamSonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSorgulaIslemInput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSorgulaIslemInput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.VitTosSorgulaIslemIstek TopluIslemIstek;
        
        public TopluOdemeSorgulaIslemInput()
        {
        }
        
        public TopluOdemeSorgulaIslemInput(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, TOS.VitTosSorgulaIslemIstek TopluIslemIstek)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.TopluIslemIstek = TopluIslemIstek;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeSorgulaIslemOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeSorgulaIslemOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DurumKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DurumKoduAciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public TOS.VitTosSorgulaIslemSonuc[] OdemeSonucListesi;
        
        public TopluOdemeSorgulaIslemOutput()
        {
        }
        
        public TopluOdemeSorgulaIslemOutput(string DurumKodu, string DurumKoduAciklama, TOS.VitTosSorgulaIslemSonuc[] OdemeSonucListesi)
        {
            this.DurumKodu = DurumKodu;
            this.DurumKoduAciklama = DurumKoduAciklama;
            this.OdemeSonucListesi = OdemeSonucListesi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeAdSoyadKontrolInput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeAdSoyadKontrolInput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOS.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AliciAdSoyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string AliciBankaKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AliciHesapIbanNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string KurumKodu;
        
        public TopluOdemeAdSoyadKontrolInput()
        {
        }
        
        public TopluOdemeAdSoyadKontrolInput(TOS.SecuredWebServiceHeader SecuredWebServiceHeader, string AliciAdSoyad, string AliciBankaKodu, string AliciHesapIbanNo, string KurumKodu)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.AliciAdSoyad = AliciAdSoyad;
            this.AliciBankaKodu = AliciBankaKodu;
            this.AliciHesapIbanNo = AliciHesapIbanNo;
            this.KurumKodu = KurumKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopluOdemeAdSoyadKontrolOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopluOdemeAdSoyadKontrolOutput
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOS.AdSoyadKontrolSonuc AdSoyadKontrolSonuc;
        
        public TopluOdemeAdSoyadKontrolOutput()
        {
        }
        
        public TopluOdemeAdSoyadKontrolOutput(TOS.AdSoyadKontrolSonuc AdSoyadKontrolSonuc)
        {
            this.AdSoyadKontrolSonuc = AdSoyadKontrolSonuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ITosServiceChannel : TOS.ITosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TosServiceClient : System.ServiceModel.ClientBase<TOS.ITosService>, TOS.ITosService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TosServiceClient() : 
                base(TosServiceClient.GetDefaultBinding(), TosServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TosServiceClient.GetBindingForEndpoint(endpointConfiguration), TosServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TOS.TopluOdemeOutput VitTosIslem(TOS.TopluOdemeInput request)
        {
            return base.Channel.VitTosIslem(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeOutput> VitTosIslemAsync(TOS.TopluOdemeInput request)
        {
            return base.Channel.VitTosIslemAsync(request);
        }
        
        public TOS.TopluOdemeSwiftOutput VitTosSwiftIslem(TOS.TopluOdemeSwiftInput request)
        {
            return base.Channel.VitTosSwiftIslem(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeSwiftOutput> VitTosSwiftIslemAsync(TOS.TopluOdemeSwiftInput request)
        {
            return base.Channel.VitTosSwiftIslemAsync(request);
        }
        
        public TOS.TopluOdemeIptalOutput VitTosIptal(TOS.VitTosIptalIstek request)
        {
            return base.Channel.VitTosIptal(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeIptalOutput> VitTosIptalAsync(TOS.VitTosIptalIstek request)
        {
            return base.Channel.VitTosIptalAsync(request);
        }
        
        public TOS.TopluOdemeSmsSifreGonderOutput SmsSifreGonder(TOS.SmsSifreGonderIstek request)
        {
            return base.Channel.SmsSifreGonder(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeSmsSifreGonderOutput> SmsSifreGonderAsync(TOS.SmsSifreGonderIstek request)
        {
            return base.Channel.SmsSifreGonderAsync(request);
        }
        
        public TOS.TopluOdemeSmsSifreOnayOutput SmsSifreOnay(TOS.SmsSifreOnayIstek request)
        {
            return base.Channel.SmsSifreOnay(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeSmsSifreOnayOutput> SmsSifreOnayAsync(TOS.SmsSifreOnayIstek request)
        {
            return base.Channel.SmsSifreOnayAsync(request);
        }
        
        public TOS.TopluOdemeOnayTamamOutput OnayTamam(TOS.OnayTamamIstek request)
        {
            return base.Channel.OnayTamam(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeOnayTamamOutput> OnayTamamAsync(TOS.OnayTamamIstek request)
        {
            return base.Channel.OnayTamamAsync(request);
        }
        
        public TOS.TopluOdemeSorgulaIslemOutput VitTosSorgulaIslem(TOS.TopluOdemeSorgulaIslemInput request)
        {
            return base.Channel.VitTosSorgulaIslem(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeSorgulaIslemOutput> VitTosSorgulaIslemAsync(TOS.TopluOdemeSorgulaIslemInput request)
        {
            return base.Channel.VitTosSorgulaIslemAsync(request);
        }
        
        public TOS.TopluOdemeAdSoyadKontrolOutput KontrolEtAdSoyadHesapBilgisi(TOS.TopluOdemeAdSoyadKontrolInput request)
        {
            return base.Channel.KontrolEtAdSoyadHesapBilgisi(request);
        }
        
        public System.Threading.Tasks.Task<TOS.TopluOdemeAdSoyadKontrolOutput> KontrolEtAdSoyadHesapBilgisiAsync(TOS.TopluOdemeAdSoyadKontrolInput request)
        {
            return base.Channel.KontrolEtAdSoyadHesapBilgisiAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITosService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITosService))
            {
                return new System.ServiceModel.EndpointAddress("https://vbtestservice.vakifbank.com.tr/Odemeler.Tos/STosService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITosService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITosService,
        }
    }
}
